language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t ibrizuela/docker-react -f Dockerfile.dev .

script:
  - docker run ibrizuela/docker-react npm run test -- --coverage
